### ISSUE TITLE
Exception: 'SonarrQueueDetail' object has no attribute 'timeleft'

### ISSUE THREAD

**Issue by NanoSector** [tkdrob/aiopyarr#60]
### Checklist

- [X] I'm running the newest version <https://github.com/tkdrob/aiopyarr/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

This issue was first reported in Home Assistant:
https://github.com/home-assistant/core/issues/81508

The [code snippet inside Home Assistant](https://github.com/home-assistant/core/blob/d62bac9c5948cb7d9c89cb25ac8a0cd1d63906e0/homeassistant/components/sonarr/coordinator.py#L118) is:

```python
class QueueDataUpdateCoordinator(SonarrDataUpdateCoordinator[SonarrQueue]):
    """Queue update coordinator."""

    async def _fetch_data(self) -> SonarrQueue:
        """Fetch the data."""
        return await self.api_client.async_get_queue(
            include_series=True, include_episode=True
        )
```

This seems to stem from PR #56 which adds a check on this property. My theory is that not all models contain this property which causes the library to raise the exception below.

### Logs

```text
2022-11-03 11:54:59.789 ERROR (MainThread) [homeassistant.components.sonarr] Unexpected error fetching sonarr data: 'SonarrQueueDetail' object has no attribute 'timeleft'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiopyarr/request_client.py", line 183, in _async_request
    response = BaseModel(
  File "/usr/local/lib/python3.10/site-packages/aiopyarr/models/base.py", line 95, in __init__
    value = generate_data(value, datatype)
  File "/usr/local/lib/python3.10/site-packages/aiopyarr/models/base.py", line 78, in generate_data
    return datatype(data)
  File "/usr/local/lib/python3.10/site-packages/aiopyarr/models/base.py", line 116, in __init__
    self.__post_init__()
  File "/usr/local/lib/python3.10/site-packages/aiopyarr/models/sonarr.py", line 193, in __post_init__
    self.records = [SonarrQueueDetail(record) for record in self.records]
  File "/usr/local/lib/python3.10/site-packages/aiopyarr/models/sonarr.py", line 193, in <listcomp>
    self.records = [SonarrQueueDetail(record) for record in self.records]
  File "/usr/local/lib/python3.10/site-packages/aiopyarr/models/base.py", line 116, in __init__
    self.__post_init__()
  File "/usr/local/lib/python3.10/site-packages/aiopyarr/models/sonarr.py", line 176, in __post_init__
    super().__post_init__()
  File "/usr/local/lib/python3.10/site-packages/aiopyarr/models/request_common.py", line 165, in __post_init__
    and self.timeleft == "00:00:00"
AttributeError: 'SonarrQueueDetail' object has no attribute 'timeleft'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/sonarr/coordinator.py", line 67, in _async_update_data
    return await self._fetch_data()
  File "/usr/src/homeassistant/homeassistant/components/sonarr/coordinator.py", line 118, in _fetch_data
    return await self.api_client.async_get_queue(
  File "/usr/local/lib/python3.10/site-packages/aiopyarr/sonarr_client.py", line 137, in async_get_queue
    return await self._async_request("queue", params=params, datatype=SonarrQueue)
  File "/usr/local/lib/python3.10/site-packages/aiopyarr/request_client.py", line 207, in _async_request
    raise ArrException(self, ex) from ex
aiopyarr.exceptions.ArrException: 'SonarrQueueDetail' object has no attribute 'timeleft'
```

**Comment by NanoSector** [comment]
Can reproduce this by modifying the example code in the README, so this is not a Home Assistant bug.

```python
"""Example usage of aiopyarr."""
import asyncio
from aiopyarr.models.host_configuration import PyArrHostConfiguration
from aiopyarr.sonarr_client import SonarrClient

IP = "IP"
TOKEN = "TOKEN"


async def async_example():
    """Example usage of aiopyarr."""
    host_configuration = PyArrHostConfiguration(hostname=IP, port=80, api_token=TOKEN)
    async with SonarrClient(host_configuration=host_configuration) as client:
        print(await client.async_get_queue(include_series=True, include_episode=True))


asyncio.get_event_loop().run_until_complete(async_example())
```

**Comment by tkdrob** [comment]
Hi. Your theory is on the right track but still incorrect. All 4 clients have `timeleft` in the model but shows no attribute if `timeleft` is not in the json response for each item in the queue. I have yet to notice this in my Sonarr instance. Can you post your Sonarr version? I'm curious if it is that or some condition when `timeleft` is not provided.

if you instead do the below, we can see the json object as a dictionary. Please share one that does not have the `timeleft` key. Thanks
```
print((await client.async_get_queue(include_series=True, include_episode=True)).attributes)
```

Edit: Looks like that won't work either. Can you get your queue by using postman or put a print statement right after the below to capture the resulting dictionary?https://github.com/tkdrob/aiopyarr/blob/07d120c39bed7a1fb7d910b5b4752f962f2a1d17/aiopyarr/request_client.py#L176

**Comment by NanoSector** [comment]
TimeLeft is nullable in the Sonarr API: https://github.com/Sonarr/Sonarr/blob/6660e0c3f37fade91d39141b2830dba4e20a46e2/src/Sonarr.Api.V3/Queue/QueueResource.cs#L28
and: https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/DownloadClientItem.cs#L18

This seems to be calculated directly from qBittorrent so it might be download client specific: https://github.com/Sonarr/Sonarr/blob/6660e0c3f37fade91d39141b2830dba4e20a46e2/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs#L562

If the torrent is stalled (has an enormous ETA) the value is set to null, and therefore does not seem to be included in the JSON response.

Here's a stripped JSON response from a request:
```
{
  "page": 1,
  "pageSize": 20,
  "sortKey": "timeleft",
  "sortDirection": "descending",
  "totalRecords": 1,
  "records": [
    {
      "seriesId": 0,
      "episodeId": 0,
      "series": {
        "title": "REDACTED",
        "sortTitle": "REDACTED",
        "status": "continuing",
        "ended": "False",
        "overview": "REDACTED",
        "network": "REDACTED",
        "airTime": "22:00",
        "images": [
          {
            "coverType": "poster",
            "url": "REDACTED"
          },
          {
            "coverType": "fanart",
            "url": "REDACTED"
          }
        ],
        "seasons": [
          {
            "seasonNumber": 1,
            "monitored": "True"
          },
          {
            "seasonNumber": 2,
            "monitored": "True"
          }
        ],
        "year": 2019,
        "path": "REDACTED",
        "qualityProfileId": 1,
        "languageProfileId": 1,
        "seasonFolder": "True",
        "monitored": "True",
        "useSceneNumbering": "False",
        "runtime": 42,
        "tvdbId": 0,
        "tvRageId": 0,
        "tvMazeId": 0,
        "firstAired": "REDACTED",
        "seriesType": "standard",
        "cleanTitle": "REDACTED",
        "imdbId": "REDACTED",
        "titleSlug": "REDACTED",
        "genres": [
          "Drama",
          "Reality"
        ],
        "tags": [],
        "added": "2019-12-25T16:09:55.764012Z",
        "ratings": {
          "votes": 0,
          "value": 0.0
        },
        "id": 127
      },
      "episode": {
        "seriesId": 127,
        "tvdbId": 7449738,
        "episodeFileId": 0,
        "seasonNumber": 1,
        "episodeNumber": 1,
        "title": "REDACTED",
        "airDate": "2019-11-17",
        "airDateUtc": "2019-11-18T03:00:00Z",
        "overview": "REDACTED",
        "hasFile": "False",
        "monitored": "True",
        "absoluteEpisodeNumber": 1,
        "unverifiedSceneNumbering": "False",
        "id": 18521
      },
      "language": {
        "id": 1,
        "name": "English"
      },
      "quality": {
        "quality": {
          "id": 9,
          "name": "HDTV-1080p",
          "source": "television",
          "resolution": 1080
        },
        "revision": {
          "version": 1,
          "real": 0,
          "isRepack": "False"
        }
      },
      "size": 2192234201.0,
      "title": "REDACTED",
      "sizeleft": 2807513.0,
      "status": "warning",
      "trackedDownloadStatus": "ok",
      "trackedDownloadState": "downloading",
      "statusMessages": [],
      "errorMessage": "The download is stalled with no connections",
      "downloadId": "REDACTED",
      "protocol": "torrent",
      "downloadClient": "qBittorrent",
      "indexer": "REDACTED",
      "outputPath": "REDACTED",
      "id": 0
    }
  ]}
```

**Comment by tkdrob** [comment]
I'm thinking it's download client specific as well.

**Comment by tkdrob** [comment]
What did the warning status exactly mean? I assume the item was not actually downloading even though `trackedDownloadState` says it is.

**Comment by NanoSector** [comment]
> What did the warning status exactly mean? I assume the item was not actually downloading even though `trackedDownloadState` says it is.

I'm assuming the warning status and errorMessage are linked, i.e. the download is stalled.

**Comment by tkdrob** [comment]
Do you have `timeleft` in any of your queue items?

**Comment by NanoSector** [comment]
Yes, the ones that are not stalled work properly. If I remove the stalled downloads from Sonarr the library does work properly.

I can only provide more traces tomorrow night - but I doubt they will contain more information beyond the fact the field does exist for downloads which are actually active.

Regardless of if the field is present in my data samples or not - Sonarr marks the field as nullable and it is the ultimate source of truth, so this (and other occurrences or different fields?) need fixing.

I'm unsure if the PR I opened is the wanted fix as clients of this library will practically need the same check - maybe it is better to provide a default value of null (or the python equivalent, I'm not very familiar with the language) if the field is not present.
